about.html
docs.html
index.html
js/filesaver.js
js/jquery-1.12.3.js
js/savetext.js
js/syntax.js
licenses/BootStrap/LICENSE.txt
licenses/FileSaver/LICENSE.md
licenses/jQuery/LICENSE.txt

- bugfixes
- implemented *.mas downloading
- changes to file uploading system
- imported jQuery.js and FileSaver.js
- inserted LICENSEs
- changes to formatting for all webpages
- updated code to V2 Beta

Beta Version 2 Release

---

about.html
docs.html
index.html
js/filesaver.js
js/jquery-1.12.3.js
js/savetext.js
js/syntax.js
licenses/BootStrap/LICENSE.txt
licenses/FileSaver/LICENSE.md
licenses/jQuery/LICENSE.txt

- bugfixes
- implemented *.mas downloading
- changes to file uploading system
- imported jQuery.js and FileSaver.js
- inserted LICENSEs
- changes to formatting for all webpages
- updated code to V2 Beta

Beta Version 2 Release UPDATED

---

README.md
about.html
css/style.css
docs.html
index.html
js/menucmd.js

Beta v3.1a - Interface Update
- bootstrap updates
- cleaner UI

Beta v3.1a - Interface Update

---

index.html

update index.html for message.
Tells the user that CodeMirror cannot support Mobile Devices.

update index.html for message

---

index.html

moving alert box

---

about.html
css/codemirror.css
css/style.css
docs.html
index.html
js/anyword-hint.js
js/showhint.js

update to Beta v3.1.10

---

about.html
docs.html
index.html

blog link update

---

about.html
css/style.css
docs.html
index.html

Beta v3.1.11 Update 
- removal of warning
- updated I/O
- fixed some bugs
- moved Output Type to bottom action bar.

Beta v3.1.11 Update 

---

.travis.yml
Gruntfile.js
README.md
package.json
src/css/style.css
src/templates/about.ejs
src/templates/partials/nav.ejs

This is a test to see how Travis CI reacts to the change.
Do not merge until Travis succeeds.

Add support for htmllint

---

src/js/interface.js

Adds the accidentally removed menu options

Add menu options again

---

src/css/bootstrap-tour.css
src/js/ext/bootstrap-tour.js

bootstrap-tour test
> REVERT IF FAIL

bootstrap-tour test

---

README.md
package.json

This marks the official release of v0.5.0

[U] Version 0.5.0 Official Update

---

src/css/style.css

Updated code to:
```
#output-log, #register-log {
padding: 0.5em 1em;
text-align: right;
font-family: sans-serif;
}
#output-log {
border-top: 0.1em solid #ccc;
font-family: sans-serif;
}
```

[UI] [P] font changes to register log

---

src/js/interface.js
src/js/marie.js
src/templates/index.ejs

Preliminary implementation of #54.
Does not update the data path visualization yet.

Preliminary implementation for stepping back

---

src/images/diagrams/drawing_plain.svg

- new ALU control wires
- new timing signal lights
- added labels to existing and new control signals
- removed the register control wires from the memory
- rearranged layout a little bit

Improved datapath SVG object

---

src/css/style.css
src/js/datapath.js
src/js/interface.js
src/js/marie.js
src/templates/index.ejs
src/templates/partials/nav.ejs

Also:
- time sequence signal lights now works
- fixed some bugs
- datapath appears to be reading from memory when it is not
- datapath doesn't show registers/memory that are being read and written to at the same time

Datapath: added display for instructions and micro-instructions

---

README.md
src/js/tour.js

- added code so that the localstorage variable tourComplete is created if it does not exist onload()
- moved rest of code so when Tour button is clicked it will run. (hopefully)
- fixed some silly mistake from previous pull request (https://github.com/MARIE-js/MARIE.js/pull/71) which in turn caused [build #101](https://travis-ci.org/MARIE-js/MARIE.js/builds/142099302) to fail

[UI] [P] tour.js patch

---

README.md
package.json
src/js/tour.js
src/templates/partials/nav.ejs

v0.5.3 update
- tour.js redesign added following to sections
```
smartPlacement: true,
element: "#brand",
```
- fixed Rerun Tour feature
```
$( "#starttour" ).click(function() {
window.localStorage.removeItem('tour_current_step');
window.localStorage.removeItem('tour_end'); //removes tour variable
location.reload(); //reload page
});
```

[U] v0.5.3 update

---

src/js/autocomplete.js

- a crude way of fixing autocomplete.js to add a space

[P] autocomplete fix

---

src/css/style.css
src/images/diagrams/drawing_plain.svg
src/js/datapath.js
src/js/interface.js
src/js/marie.js
src/templates/index.ejs
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

- Layout modified slightly to fit in address/data bus
- Now has working address/data bus components
- ALU control bus now shows signals when an add or subtract micro-operation is being performed
- Highlights current micro-instruction being executed
- Now can toggle display of datapath via View > Datapath

Slight modifications to datapath

---

src/js/tour.js
src/templates/partials/nav.ejs

- update glphyicons to top menu items
- fixed issue #82  by change it to `<a href="./">`
- fixed Datapath menu item rendering tick where it datapath is ready to be used by change code to: 
```
<li><a id="dpath-menu"><span id="datapath-tick" class="glyphicon glyphicon-ok pull-right"></span> Datapath</a></li>
```

[P] [UI] Fixing some interface problems

---

README.md
src/css/style.css
src/js/datapath.js
src/js/interface.js
src/templates/index.ejs

- set delay to 1000 ms for data bus access if simulator is running in (micro)step mode
- initial illustration of ALU to register wires
Also:
- modified README file slightly
- added "Loading..." text to textarea while page is loading, and set height to 100%

[P] [UI] slightly improved datapath

---

licenses/Bootstrap Tour/LICENSE
src/css/show-hint.css
src/js/ext/codemirror.js
src/js/ext/filesaver.js
src/js/ext/show-hint.js
src/templates/partials/nav.ejs

- updated `show-hint` addon of CodeMirror
- updated `filesaver.js`
- added LICENSE files for missing dependancies

[D] dependency updates

---

src/js/datapath.js
src/js/interface.js
src/js/marie.js

(with non-symbolic operands)  if it reads a memory location that has no corresponding program instruction

datapath falls back to decoding the instruction from memory

---

.gitignore
Gruntfile.js
package.json
src/js/datapath.js
src/js/interface.js
src/js/marie.js
src/js/utility.js
src/templates/partials/header.ejs

Make sure to run `npm install`

Moved utility code into utility.js; added jsdoc; documented utility.js and marie.js

---

README.md
package.json
src/js/interface.js

- fixed issue #101 idling for more then 10 seconds, saves code to codemirror or upon window close.
- fixed issue #68  for above method as well as potential svm patch coming soon
- fixed issue #95

[U][P][UI] v0.6.0 update

---

src/js/tour.js
src/templates/partials/nav.ejs

- finishes tour upon end
- initial implementation of tour going to menu items

[P] small patch

---

src/js/interface.js
src/templates/index.ejs
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

This can be accessed via `Edit -> Preferences`.

Added preferences

---

src/js/datapath.js
src/js/interface.js
src/js/marie.js

Resolved #85 by using an argument in reglog event for which ALU operation is being used (and is undefined when no ALU operation is being used)

Resolved #85

---

README.md
package.json
src/js/interface.js
src/templates/index.ejs

- initial commit to fix new file button
- secondary updates to fix flaws with initial v0.6.5 commit

v0.6.5 cumulative update

---

README.md
package.json
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

Revert "v0.6.6 release"

---

README.md
package.json
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

Revert "Revert "v0.6.6 release""

---

README.md
package.json
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

Revert "Revert "Revert "v0.6.6 release"""

---

README.md
package.json
src/css/style.css
src/js/interface.js
src/templates/index.ejs

- fixing issue #129 through moving output selector
- some minor UI changes (changes to `style.css`, changes to div by adding `col-md-8` and `col-md-4` classes to status bar and output selector
- preliminary updates to templates.js function planned for v0.8

v0.7 update - 

---

README.md
package.json
src/js/interface.js
src/templates/index.ejs
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

- removed blog link
- added GitHub MARIE.js releases link
- added browser detection: if Browser is FireFox, display warning message, 
- added support for future functions
- fixed a few bugs

v0.7.5 update:

---

README.md
package.json
src/css/style.css
src/js/interface.js
src/templates/index.ejs

_This is an important patch_
---
This patch fixes the following: 
- allows user to set up default settings for following items:
- default Binary Groups (default value is `4`)
- default Input Values
- default Output Values
- also some graphical changes to Preference Modal UI

v0.7.15 update

---

README.md
package.json
src/js/interface.js

**THIS IS AN IMPORTANT PATCH**
---
- fixes preferences issues within `v0.7.17` and `v0.7.15`
---
Fixes Affected Version(s):
- `v0.7.17`
- `v0.7.15`

v0.7.18 patch

---

README.md
package.json
src/code/addition.mas
src/code/multiply.mas
src/js/interface.js

- added query strings
- added localtemplate for examples

v0.8.0 release 

---

README.md
package.json
src/css/bootstrap.css
src/css/style.css
src/js/interface.js
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

- v0.8.5 release
- fixing some bugs, revert to original `bootstrap.css`
- fixed some grunt-test errors

v0.8.5 release

---

README.md
package.json
src/code/multiply.mas
src/code/quicksort.mas
src/js/marie.js
src/js/tour.js
src/templates/about.ejs
src/templates/index.ejs

- **MARIE.js Core Code Changes:** improving handling of negative values to PC to fix issue #148 with negative values
- **Page Changes:** changes to about.html 
- added ToS agreement
- acknowledged @RavenKelder (Felix) for his work on demostration code
- ***Changes to tour.js:** updated tour.js for more helpful messages
- **Fixes to demo code:** uploaded quicksort.mas as demo code, updated multiply.mas to fix some changes, 
- **Fixing demo code loading system:** fixed code so that the div is hidden upon startup by adding hidden attribute to alert. `<div id="warn-missing-file" class="alert alert-warning" hidden>`, and removed `$('#warn-missing-file').hide()` from loading page code

v0.9.3 update

---

src/js/marie.js

[p] fixing a bug when sim raises an error when address = 0
changed to
```
else if(this[target] < 0){...}
```

[p] fixing a bug when sim raises an error when address = 0

---

src/js/marie.js

- shows the error message `RuntimeError: the address (address val) is out of bounds`

[p][UI] Fixing Error Message Showing that Address is out Of Bounds

---

.gitignore
src/js/interface.js
src/templates/index.ejs

I'm starting with the most annoying problem (at least for me :sweat_smile:)
The ToU modal has an "I agree" button now, and no checkbox.
I also added vim .swp files to .gitignore to make my life easier.

Fix ToU agreement modal

---

src/js/interface.js
src/templates/index.ejs

- smarter detection of empty file name
- updated so that if file name is empty default filename is chosen (`code`)
- merge extensions and then download.

[UI][P] updated custom download file

---

src/css/styleLight.css

[UI] Light Theme update

---

src/css/styleDark.css
src/js/interface.js
src/js/theme.js
src/templates/index.ejs
src/templates/partials/header.ejs

- fixed jslint errors
- added theme switcher
- moved loading code to `theme.js` for entire site support
- improved `styleDark.css`

[UI][U] theme switcher updates

---

README.md
src/css/plain.css
src/css/styleDark.css
src/css/styleLight.css
src/templates/index.ejs

- fixing css and design of index

Cumulative Update for v0.10.0-preview

---

src/css/plain.css
src/css/styleDark.css
src/js/interface.js
src/templates/index.ejs

Add automated user inputs

---

Gruntfile.js
src/js/ext/gapi.js
src/js/interface.js
src/templates/partials/nav.ejs

this is a very hackable way of doing it.
it loads file into sessionstorage, passes it through `interface.js` back to programCodeMirror

updated gapi.js so that it can read from gdrive

---

Gruntfile.js
LICENSE
licenses/NProgress/License.md
package.json
src/css/nprogress.css
src/js/ext/gapi.js
src/js/ext/nprogress.js
src/js/interface.js
src/templates/partials/header.ejs
src/templates/partials/nav.ejs

- updating gapi.js for better loading file		
- [UI] updated so that NProgress.js is used
- displays loading status using NProgress.js	
- updating navbar 
- `Hello <name>` hides upon open, when authenticated it appears and `Login` becomes hidden, oauth token is stored in localstorage for use by other functions for handshakes (this will need to be changed for security reasons in a future update)
- github points to new tab/window			
- updating sign-in icon

[UI][UX] Google Drive API and NavBar Updates

---

Gruntfile.js
src/js/ext/gapi.js
src/js/interface.js
src/templates/index.ejs
src/templates/partials/nav.ejs

_this is a proof of concept commit of saving files to google drive_
Saving files to Google Drive get be improved by adding updating functionality, say for instance when the user loads a file from Google Drive
1. it stores the fileID into sessionstorage
2. if user clicks 'Save to Google Drive' it will check sessionstorage to see if the fileID exists, if its not null (!== null || !== 0)
3. it then updates the file
4. otherwise it will just upload the file
* Note: this method will also require the folderID of the google drive location, which im unsure on how to implement at this stage

[UX] proof of concept of saving to google drive

---

src/css/plain.css
src/js/ext/gapi.js
src/js/interface.js

- Opening file with Google Picker, saves the ParentID (folderID) and the File ID (fileID) into sessionstorage, so that interface.js can use values for updating file
- Saving file to Google Drives also checks if user has opened it using the Google Picker API on MARIE.js
- When saving the file `gapi.js` checks if file ID exists to decide whether to update or upload a new file
- bug fixes for security purposes, new gapi calls must now be called with a new `oauth` token every time.

[UX][P][S] Patch for Smarter Integration of Google Drive/Picker API

---

src/js/ext/gapi.js

- handles NProgress.js to finish (`NProgress.done()`) if user cancels the user of the picker
- uses `data[google.picker.Reponse.Action]` to determine the state of the Picker
- improvements to various sections of code
- added variables for easier to handle and read

[UI][GAPI] Updated Google Picker 

---

README.md
build/about.html
build/index.html
package.json
src/css/styleDark.css
src/js/ext/gapi.js
src/js/interface.js
src/templates/about.ejs
src/templates/index.ejs

- fixed issue #265 
- improved various UI in about.html

[V][UI][UX] Version 1.0.10 release

---

build/about.html
build/index.html
src/css/styleDark.css
src/js/ext/gapi.js
src/templates/index.ejs
src/templates/partials/nav.ejs

- moved Google Login area
- added default settings for downloaing file formats

[UI][UX] Cumulative Update 

---

README.md
build/about.html
build/index.html
package.json
src/js/ext/gapi.js
src/js/interface.js
src/js/tour.js
src/templates/partials/nav.ejs

**New features**
- updating files if file is previously saved to drive
- added tour.js for Google Services
**Bug Fixes**
- probably fixed bug where browser attempts to display non-greyed out background when ToS is opened

[P][UI][UX][GAPI] v1.0.12 update

---

.gitignore
build/about.html
build/index.html
src/js/tour.js
src/templates/index.ejs
src/templates/partials/nav.ejs

- fixed displayversion bug	
- fixed tour.js bug, where first point is not on logo

[CU][P][UI][UX] Cumalative Update for User Interface

---

Gruntfile.js
README.md
build/about.html
build/index.html
package.json
src/js/ext/gapi.js
src/js/interface.js
src/templates/index.ejs
src/templates/partials/nav.ejs

- updated GAPI.js for custom file location uploading
- security fixes to gapi.js
- updated workflow of gapi.js and interface.js
- updated interaction between interface.js and gapi.js
- fixed some bugs with index.html modals
- initial folder select implementation

[U][P][UX][GAPI] v1.1.0 release

---

src/js/marie.js

This pull request fixes two small bugs. The first bug is an off-by-one error, here is a program which should assemble because it is short enough to fit into memory: [insufficient_memory_demo.mas](https://marie.js.org/#code=Hex%200000%0AHex%200001%0AHex%200002%0AHex%200003%0AHex%200004%0AHex%200005%0AHex%200006%0AHex%200007%0AHex%200008%0AHex%200009%0AHex%20000A%0AHex%20000B%0AHex%20000C%0AHex%20000D%0AHex%20000E%0AHex%20000F%0AHex%200010%0AHex%200011%0AHex%200012%0AHex%200013%0AHex%200014%0AHex%200015%0AHex%200016%0AHex%200017%0AHex%200018%0AHex%200019%0AHex%20001A%0AHex%20001B%0AHex%20001C%0AHex%20001D%0AHex%20001E%0AHex%20001F%0AHex%200020%0AHex%200021%0AHex%200022%0AHex%200023%0AHex%200024%0AHex%200025%0AHex%200026%0AHex%200027%0AHex%200028%0AHex%200029%0AHex%20002A%0AHex%20002B%0AHex%2 …

Minor bug fixes: insufficient memory and whitespace in labels

---

package-lock.json
package.json
src/syntax.ts

- Fix syntax highlighting for `LoadImmi` when there is a label
- Allow hovering over the `SkipCond` operand to show what the condition is
- Bump to 2.1.1

Fix syntax highlighting for LoadImmi
